### ISSUE TITLE
Request package be moved to JuliaSparse

### ISSUE THREAD

**Issue by Wimmerer** [JuliaSparse/SuiteSparseGraphBLAS.jl#14]
I'm doing a Julia Summer of Code updating/completing the SSGrB wrapper and providing AD chain rules for the operations. Would you be willing to have this package moved to the JuliaSparse organization? @ViralBShah will facilitate the move.

**Comment by ViralBShah** [comment]
This is a great idea. @abhinavmehndiratta If ok with you, please let me know and either @Wimmerer or I can give you owner access to JuliaSparse to facilitate the move. Naturally, we'll make sure you continue to have admin access to the package going forward.

**Comment by abhinavmehndiratta** [comment]
Seems like a good idea. Let me know the procedure, I would be happy to help.

**Comment by ViralBShah** [comment]
I've sent you an invitation to be an owner of JuliaSparse. Once you accept it, you can go to the settings in this repo and transfer the repo to the new org.

**Comment by abhinavmehndiratta** [comment]
I've transferred the ownership, are there any further steps needed ? Will I need to re-register the package ?

**Comment by Wimmerer** [comment]
Thanks @abhinavmehndiratta! I've got a fairly significant rewrite coming in a few weeks. Would you like me to ping you for review or am I good to merge things once mentors have reviewed? 

I will also credit you in the README as original author, of course.

**Comment by abhinavmehndiratta** [comment]
I don't think I'll have the time to work on this project, you can go ahead and make changes as you find suitable. All the best for your JSoC, looking forward to some great stuff !
