### ISSUE TITLE
Docstring for GBMatrix unclear on "maximum on each dimension"

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaSparse/SuiteSparseGraphBLAS.jl#72]
Perhaps this comment was added to the wrong method?

Unclear how specifying rows/cols as a positional argument could also have a default large size.

![image](https://user-images.githubusercontent.com/1438610/165018202-1b68b9ff-3545-4555-8337-fcbe47724996.png)

**Comment by Wimmerer** [comment]
Ah yes, sorry. The size used to have a default which it no longer does.
